### ISSUE TITLE
No pages at ViewPager while using DynamicFragmentsAdapter

### ISSUE THREAD

**Issue by Kolyall** [pranavpandey/dynamic-support#7]
I'm trying to use your `DynamicFragmentsAdapter` at Fragment
Here is my code of  my adapter `MyAdapter`:
```
class MyAdapter constructor(
      fragmentManager: FragmentManager
) : DynamicFragmentsAdapter(fragmentManager) {

    override fun createItem(position: Int): BaseFragment {
        return when (position) {
            0 -> MyCollectionsFragment()
            1 -> MyPlaylistsFragment()
            else -> throw IndexOutOfBoundsException("IndexOutOfBounds $position")
        }
    }

    override fun getCount(): Int {
        return 2
    }
}

```
MainFragment
```
class MainFragment : Fragment() {
override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        pagerAdapter = MainAdapter(activity?.supportFragmentManager ?: return)
        viewPager.adapter = pagerAdapter
    }
}
```
Flow of using:

in MainActivity:
```
val mainFragment = MainFragment()
transaction.replace(fragmentContainer, mainFragment, tag)
.commitAllowingStateLoss()
```
then set another fragment:
```
val otherFragment = OtherFragment()
transaction.replace(fragmentContainer, otherFragment, tag)
.commitAllowingStateLoss()
```
and then set `mainFragment` again:
```
transaction.replace(fragmentContainer, mainFragment, tag)
.commitAllowingStateLoss()
```

In result pages are restored, method `restoreState` was called, val `mPages` is filled, 
BUT `viewPager` is without pages, seems method `public Fragment getItem(int position)` was not called

**Comment by pranavpandey** [comment]
Thanks for the info!

Since v3.0.0, It uses the default support library (AndroidX) implementation as it has now all the optimizations and fixes. I will check it later but the current plan is to deprecate the `DynamicFragmentsAdapter` as no special implementation is required for now. Please check [this commit](https://github.com/pranavpandey/dynamic-support/commit/bc9c343b9ab28901b6e0c305f1e4b88051ed995f#diff-b2f63d57d190c612579d561d8429d293) for more info.

You can use [DynamicViewPagerFragment](https://github.com/pranavpandey/dynamic-support/blob/master/dynamic-support/src/main/java/com/pranavpandey/android/dynamic/support/fragment/DynamicViewPagerFragment.java) to show fragments in a `ViewPager`. Please check the implementation [here](https://github.com/pranavpandey/dynamic-support/blob/master/sample/src/main/java/com/pranavpandey/android/dynamic/support/sample/fragment/SettingsFragment.kt).
