### ISSUE TITLE
Light accent color becomes dark

### ISSUE THREAD

**Issue by subpub** [pranavpandey/dynamic-support#9]
Tried even with yellow 

How it is

![](https://i.imgur.com/oj6NOL2.jpg)

How one expects

![](https://i.imgur.com/zNAKQWd.jpg)

Is it intentional?

**Comment by subpub** [comment]
I think I figured out what the description says. It's dark on light and light on dark.

More I think about it, I feel it should be the opposite. Do you feel an extra "switch saturation" would be viable?

**Comment by pranavpandey** [comment]
Hello! Yes, it's intentional as [background aware](https://github.com/pranavpandey/dynamic-support#background-aware) is enabled for the sample which adjusts views according to their background to provide the best visibility.

Background aware always tries to show the true colors when possible. However, it can be disabled to force true colors.

```xml
<style name="App" parent="Theme.DynamicApp">
    ...
    <item name="ads_backgroundAware">disable</item>
</style>
```

OR

```java
@Override
protected void onCustomiseTheme() {
    DynamicTheme.getInstance().get().setBackgroundAware(Theme.BackgroundAware.DISABLE);
}
```

**Comment by subpub** [comment]
Awesome, thanks! Totally missed that in the readme.
